ARG mode=ce
ARG MAGENTO_VERSION=2.4.1-p1
FROM odyssee/magento:$MAGENTO_VERSION-$mode

ENV MAGENTO_ROOT /var/www/html
ENV MAGENTO_DIR magento2

####### Install LUMA #######
COPY auth.json ${MAGENTO_ROOT}/${MAGENTO_DIR}
RUN cd ${MAGENTO_ROOT}/${MAGENTO_DIR} \
  && service elasticsearch start \
  && service mysql start \
  && ./bin/magento sampledata:deploy \
  && ./bin/magento setup:upgrade \
  && ./bin/magento setup:di:compile \
  && ./bin/magento cache:clean \
  && rm ./auth.json
